var EnumHelper = {
  REQUESTS:{
    "TEST1":{
      "url":"http://localhost:8080/LibreDragon/api/test",
      "type":"GET",
      "dataType":"text"
    },
    "GAME":{
      "url":"./html/game.html",
      "type":"GET",
      "dataType":"html"
    },
    "SETTINGS":{
      "url":"./html/settings.html",
      "type":"GET",
      "dataType":"html"
    },
    "HELP":{
      "url":"./html/help.html",
      "type":"GET",
      "dataType":"html"
    },
    "OPERATION":{
      "url":"http://localhost:8080/LibreDragon/api/test/operation",
      "type":"GET",
      "dataType":"text"
    }
  }
}
